# golangci-lint configuration for Rankle Go
# Compatible with golangci-lint v1.62+

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - build
    - .gopath
    - .gocache

linters:
  enable-all: true
  disable:
    # Deprecated/removed linters
    - maligned
    - interfacer
    - golint
    - scopelint
    - exhaustivestruct
    - ifshort
    - deadcode
    - varcheck
    - structcheck
    - nosnakecase

    # Problematic in newer versions
    - depguard  # Has configuration issues in v1.62+

    # Too opinionated
    - funlen
    - gocognit
    - nestif
    - nlreturn
    - wsl
    - godox
    - testpackage
    - wrapcheck
    - exhaustruct
    - varnamelen
    - tagliatelle
    - ireturn
    - cyclop
    - gochecknoglobals
    - gochecknoinits
    - paralleltest
    - tparallel
    - forcetypeassert
    - maintidx

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  goimports:
    local-prefixes: github.com/javicosvml/rankle-go

  govet:
    enable-all: true
    disable:
      - shadow

  lll:
    line-length: 140

  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
        - funlen

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
