# golangci-lint configuration
# Compatible with golangci-lint v2.x

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - build

linters:
  enable-all: true
  disable:
    # Deprecated linters
    - maligned
    - interfacer
    - golint
    - scopelint
    - exhaustivestruct
    - ifshort
    - deadcode
    - varcheck
    - structcheck
    - nosnakecase

    # Too opinionated
    - funlen
    - gocognit
    - nestif
    - nlreturn
    - wsl
    - godox
    - testpackage
    - wrapcheck
    - exhaustruct
    - varnamelen
    - tagliatelle
    - ireturn
    - cyclop

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
